### ISSUE TITLE
Viewability-Insights didn´t measure 100% despite the ad is full in viewport

### ISSUE THREAD

**Issue by Printi71** [googleads/googleads-viewability-insights-extension#6]
We are using a creative template for the understitial-ad, but we can´t reach 100% viewability, it is almost about +/- 75% when we scroll over the ad. But if the ad is 100% in viewport and we refresh the page then we get about 95 - 100% viewability. Usually the user isn`t refreshing the page so this is a problem for us and our viewability benchmarks.

With the url-parameter we call our test lineitem.

1. Go to: https://www.harpersbazaar.de/fashion/dieses-vintage-kleid-ist-zurueck-lieben?atf_url_targeting&atf=understitial_test
3. Scroll down to ad-slot 'content_1'

**Expected behavior**
We are awaiting 100% viewability as shown on the screen.

**Screenshots**

Scrolling over the ad:

<img width="1189" alt="understitial_viewability_75" src="https://github.com/googleads/googleads-viewability-insights-extension/assets/132053651/135c086e-9bed-47cb-960c-601d7ae31370">

Reload the page when the ad is 100% in viewport:

<img width="1007" alt="understitial_viewability_95" src="https://github.com/googleads/googleads-viewability-insights-extension/assets/132053651/c834da44-b847-485f-a5b9-8ed48162d381">

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Version [Version 126.0.6478.115 (Offizieller Build) (64-Bit)]

**Smartphone (please complete the following information):**

**Additional context**
Don´t worry about the size displayed in the ad (640x920). This is for double density/high resolution displays.
It doesn`t matter if we measure it on desktop or mobile.

**Comment by MarkusBordihn** [comment]
Thank you for your feedback and report.

In this case, the extension is functioning as intended, correctly displaying a visibility of 95%. The issue lies with the visual representation (green rectangle) of the visible area, which is not accurate for this highly dynamic construct.

If you inspect the "GoogleActiveViewInnerContainer" within the Iframe using Developer Tools, you’ll see that it is larger or shifted compared to the Iframe container, as illustrated below:

![image](https://github.com/googleads/googleads-viewability-insights-extension/assets/12183293/d18b57a5-0614-4382-b606-6c0a0d40463d)

Due to this discrepancy, the viewability will almost never reach 100% because the Viewability Container is shifted or larger than the Iframe container.

Please understand that I cannot provide individual support for custom solutions and related issues. 
However, I will investigate potential improvements for the visual representation (green rectangle) for such dynamic constructs.

It would be very helpful if you could keep this test page live for the next two weeks. Thanks.

**Comment by Printi71** [comment]
Hi Markus,

many thanks for the quick reply. Yes, you can use the url for the next weeks. The test-lineitem is unlimited in time. We use it regularly.
I will send your answer to our developer so he can also think about what he can do maybe.

Best
Christian

**Comment by Printi71** [comment]
Hi Markus,

sorry for not replying to your comment from the 3rd of September. I have been on vacation and your message must have been lost in the mass. Thank you very much for your work! We will have an eye on it if we see an improvement on our KPIs.
Were the already installed browser add-ons updated automatically?

Best
Christian

**Comment by MarkusBordihn** [comment]
Hi Christian,
the latest version, 1.0.0, is currently under review in the Chrome Store. Once approved, it will automatically be available to all users.

You can also force the update by clicking the "Update" button in the Extensions screen as soon as it’s approved. The review process typically takes 1–2 days.

This version introduces a new "orange" indicator for cases where the view is around 100% but lacks a viewability ping, making it easier to identify partial viewability issues.

**Comment by Printi71** [comment]
Hi Markus,
sounds really great. I´m looking forward for the updated version. 
Thank you for your effort!

Best
Christian
